### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by genobobeno** [zhanghao-njmu/openapi#1]
I installed the package and pushed my api key, and tried to run a few commands with no success due to an SSL certificate problem:

    > api_setup(api_url = "https://api.openai.com", api_key = Sys.getenv("OPENAI_API_KEY"))
    > q <- ChatGPT$new()
    > o.q <- code_comment(q.df$ALRT_QRY[1])

    Error in function (type, msg, asError = TRUE)  : 
       SSL certificate problem: unable to get local issuer certificate
    
    > q$chat("What is pharmacogenomics?")

    Error in function (type, msg, asError = TRUE)  : 
      SSL certificate problem: unable to get local issuer certificate

**Comment by zhanghao-njmu** [comment]
You can disable SSL using the following command:
```
httr::set_config(httr::config(ssl_verifypeer = FALSE, ssl_verifyhost = FALSE))
```

**Comment by zhanghao-njmu** [comment]
This issue has been fixed in the lasted version.
