### ISSUE TITLE
invalidateLater?

### ISSUE THREAD

**Issue by stevepowell99** [zhanghao-njmu/openapi#2]
thanks for a great package.
Just wondering what the invalidateLater setting does? If I have a very laggy or noisy connection, can I set this number larger to get a less smooth but more stable streaming process?

**Comment by zhanghao-njmu** [comment]
The purpose of `invalidateLater` is to continuously render the UI based on the response from chatgpt (which is written to `stream_file`) to achieve stream output, until the response is complete.

Therefore, the stream effect is determined by `invalidateLater`, which is set to **50 milliseconds** by default. The higher the value, the longer the rendering interval, and the less smooth the display effect. 

However, the lower limit of the stream effect is determined by the content generation speed in `stream_file`.

**Comment by stevepowell99** [comment]
thanks, so do you know what determines the content generation speed in stream_file? does it depend on hardware, length of texts, number of current connections?

**Comment by zhanghao-njmu** [comment]
The content generation speed mainly depends on the response speed of the API server you are requesting. Currently, OpenAI's official servers have a high load and the response speed may be slower at times. In comparison, Azure's response will be faster.

**Comment by stevepowell99** [comment]
thanks, so it is possible to connect to the Azure API using api_setup() ?

**Comment by zhanghao-njmu** [comment]
Yes. However, openai has just updated its method. It is recommended to install the latest version and set up using the following code:
```
## Azure OpenAI API
api_base <- "https://xxxxxx.openai.azure.com"
api_key <- "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
api_setup(
  api_base = api_base, api_key = api_key,
  api_type = "azure", azure_deployment = "openai/deployments/[your_deployment_name]", api_version = "2023-03-15-preview"
)
```
